### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by UcasCore** [Ezra-Yu/ACCV2022_FGIA_1st#11]
请问这次比赛的数据集还有其他下载途径吗？官网只能报名才能下载数据集，但报名时间早已经过去了。

**Comment by Ezra-Yu** [comment]
目前我也没有，你可以尝试联系一下主办方。

目前公开的比较类似的数据集有[inaturalist-2018](https://paperswithcode.com/sota/image-classification-on-inaturalist-2018)，数据集类型以及特征有些相似。不过这个比赛的数据集会更脏一些。

**Comment by UcasCore** [comment]
好的好的，万分感谢！
