### ISSUE TITLE
关于MAE的疑问

### ISSUE THREAD

**Issue by bobo0810** [Ezra-Yu/ACCV2022_FGIA_1st#12]
@Ezra-Yu  非常感谢您的工作。当前有些疑问，麻烦解惑~

目的：MAE预训练的资源和成本过高，想了解收益如何？
问题：MAE是否有消融实验结果？如果没有，MAE-ViT在比赛过程中的提升过程也OK~

再次感谢，期待回复~

**Comment by Ezra-Yu** [comment]
> 问题：MAE是否有消融实验结果？如果没有，MAE-ViT在比赛过程中的提升过程也OK~

非常抱歉，由于时间紧迫，没有做相关实验。
做过800e和1600e的对比实验，1600e会更好。

我们使用的预训练中： ViT使用的MAE自己训练的权重，SwinV2是直接使用官方在simMIM-21k的权重。最后ViT的更好（+~0.7），可能原因有两个1.ViT本身的模型上限更高。2，使用了MAE训练了比赛数据集。
