### ISSUE TITLE
关于自蒸馏

### ISSUE THREAD

**Issue by HaoLiuHust** [Ezra-Yu/ACCV2022_FGIA_1st#14]
![image](https://github.com/Ezra-Yu/ACCV2022_FGIA_1st/assets/7233091/a150d5fb-5da3-4a4a-ab26-89f14d63ca39)
流程中的自蒸馏的代码在哪儿，是指使用伪标签训练么？

**Comment by Ezra-Yu** [comment]
对，这里是制作伪标签的代码 https://github.com/Ezra-Yu/ACCV2022_FGIA_1st/blob/master/tools/creat_pseudo.py

**Comment by HaoLiuHust** [comment]
好的，多谢
